# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/fytinnovations/jobmanager/models/jobtype/columns.yaml

# Model Class name
modelClass: Fytinnovations\JobManager\Models\JobType

# List Title
title: fytinnovations.jobmanager::lang.job_types.list_title

# Link URL for each record
recordUrl: fytinnovations/jobmanager/jobtypes/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Displays a tree hierarchy for parent/child records
showTree: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
